# Generated by Django 3.1.2 on 2020-10-07 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.RemoveField(
            model_name='order',
            name='start_date',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
