# Generated by Django 3.1.2 on 2020-10-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201008_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='effects',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='medicine',
            name='generic_name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='medicine',
            name='side_effects',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='medicine',
            name='stock',
            field=models.IntegerField(default=1),
        ),
    ]
