# Generated by Django 3.0.3 on 2020-10-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201008_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='slug',
            field=models.SlugField(default=1, unique=True),
        ),
    ]
