# Generated by Django 3.0.3 on 2020-10-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_medicine_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='slug',
            field=models.SlugField(default=models.AutoField(primary_key=True, serialize=False), unique=True),
        ),
    ]
