# Generated by Django 3.0.3 on 2020-10-08 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
