# Generated by Django 3.0.6 on 2020-10-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201009_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_json',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
